info:
  type: d_product
  title: Marine-XT 550
field_product_image:
  type: image
  data:
    - file: d_product_init/d_product_init_machine-xt-550-1.png
      alt: Title / Subtitle
    - file: d_product_init/d_product_init_machine-xt-550-2.png
      alt: Title / Subtitle
    - file: d_product_init/d_product_init_machine-xt-550-3.png
      alt: Title / Subtitle
    - file: d_product_init/d_product_init_machine-xt-550-4.png
      alt: Title / Subtitle
  dst_dir: demo
body:
  type: text
  data: Engine for small motor boats. Mounted outside the boat. 40 horsepower ensures excellent performance and low fuel consumption.
field_product_categories:
  type: taxonomy
  data:
    vid: d_product_categories
    terms:
      - Boat engines
field_tags:
  type: taxonomy
  data:
    vid: tags
    terms:
      - Airplanes
field_d_product_link:
  type: cta
  data:
    link: #
    text: Buy now
