info:
  type: d_product
  title: Auto Engine ST 40
field_product_image:
  type: image
  data:
    - file: d_product_init/d_product_init_auto-engine-st-40-1.png
      alt: Title / Subtitle
    - file: d_product_init/d_product_init_auto-engine-st-40-2.png
      alt: Title / Subtitle
    - file: d_product_init/d_product_init_auto-engine-st-40-3.png
      alt: Title / Subtitle
    - file: d_product_init/d_product_init_auto-engine-st-40-4.png
      alt: Title / Subtitle
  dst_dir: demo
body:
  type: text
  data: Car engine for small cars. Manufactured for the first time in 2010. Since then, several versions with different powers have been created.
field_product_categories:
  type: taxonomy
  data:
    vid: d_product_categories
    terms:
      - Car engines
field_tags:
  type: taxonomy
  data:
    vid: tags
    terms:
      - Wooden
      - Violin
      - Music
field_d_product_link:
  type: cta
  data:
    link: #
    text: Buy now
