info:
  type: d_product
  title: Classic Antique Violin Handmade Wooden Coffin Case for restoration
field_d_product_media:
  type: media_image
  directory: demo
  files:
    - path: d_product_init/demo_event_4.jpg
      alt: Title / Subtitle
    - path: d_product_init/demo_event_2.jpg
      alt: Title / Subtitle
    - path: d_product_init/demo_event_3.jpg
      alt: Title / Subtitle
    - path: d_product_init/demo_event_1.jpg
      alt: Title / Subtitle
body:
  type: text
  data: Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse
    a pellentesque dui, non feils. Maecenas malesuada elit lecut felis, malesuada ultricies.
    Curabur et ligule. Ut molestie a, ultricies porta una, fermatum in, dolor.
field_product_categories:
  type: taxonomy
  data:
    vid: d_product_categories
    terms:
      - Musical instruments
field_tags:
  type: taxonomy
  data:
    vid: tags
    terms:
      - Wooden
      - Violin
      - Music
field_d_product_link:
  type: cta
  data:
    link: #
    text: Buy now
