info:
  type: d_product
  title: Super Charged Engine
field_d_product_media:
  type: media_image
  directory: demo
  files:
    - path: d_product_init/d_product_init_super-charged-engine-1.jpg
      alt: Title / Subtitle
    - path: d_product_init/d_product_init_super-charged-engine-2.jpg
      alt: Title / Subtitle
    - path: d_product_init/d_product_init_super-charged-engine-3.jpg
      alt: Title / Subtitle
body:
  type: text
  data: Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse
    a pellentesque dui, non feils. Maecenas malesuada elit lecut felis, malesuada ultricies.
    Curabur et ligule. Ut molestie a, ultricies porta una, fermatum in, dolor.
field_product_categories:
  type: taxonomy
  data:
    vid: d_product_categories
    terms:
      - Diesel Engines
field_tags:
  type: taxonomy
  data:
    vid: tags
    terms:
      - Cars
field_d_product_link:
  type: cta
  data:
    link: #
    text: Buy now
