core.entity_form_display.node.content_page.default:
  add:
    content:
      field_header_layout:
        region: content
        type: options_select
field.field.node.content_page.field_header_layout:
  change:
    expected:
      required: false
    new:
      required: true
