core.entity_view_display.media.d_image.d_blog_image:
  add:
    dependencies:
      module:
        - lazy
paragraphs.paragraphs_type.d_p_blog_image:
  add:
    icon_default: null
paragraphs.paragraphs_type.d_p_blog_text:
  add:
    icon_default: null
