core.entity_form_display.paragraph.d_p_side_by_side.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_side_by_side.field_d_cta_link
        - field.field.paragraph.d_p_side_by_side.field_d_media_icon
      module:
        - link_attributes
        - media_library
    third_party_settings:
      field_group:
        group_settings:
          children:
            - field_d_media_icon
            - field_d_cta_link
    content:
      field_d_cta_link:
        weight: 16
        settings:
          placeholder_url: ''
          placeholder_title: ''
          enabled_attributes:
            id: true
            name: true
            target: true
            rel: true
            class: true
            accesskey: true
            aria-label: false
            title: false
        third_party_settings: {  }
        type: link_attributes
        region: content
      field_d_media_icon:
        weight: 14
        settings:
          media_types: {  }
        third_party_settings: {  }
        type: media_library_widget
        region: content
core.entity_view_display.paragraph.d_p_side_by_side.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_side_by_side.field_d_cta_link
        - field.field.paragraph.d_p_side_by_side.field_d_media_icon
      module:
        - link
    content:
      field_d_cta_link:
        weight: 6
        label: hidden
        settings:
          trim_length: 80
          url_only: false
          url_plain: false
          rel: ''
          target: ''
        third_party_settings: {  }
        type: link
        region: content
      field_d_media_icon:
        weight: 7
        label: hidden
        settings:
          view_mode: d_icon
          link: false
        third_party_settings: {  }
        type: entity_reference_entity_view
        region: content
field.field.paragraph.d_p_side_by_side.field_d_p_sbs_items:
  add:
    settings:
      handler_settings:
        target_bundles:
          d_p_media: d_p_media
        target_bundles_drag_drop:
          d_p_media:
            enabled: true
            weight: 50
