core.entity_form_display.paragraph.d_p_side_by_side.default:
  add:
    content:
      field_d_long_text:
        type: text_textarea
        weight: 1
        region: content
        settings:
          rows: 5
          placeholder: ''
        third_party_settings: {  }
      field_d_main_title:
        type: string_textfield
        weight: 0
        region: content
        settings:
          size: 60
          placeholder: ''
        third_party_settings: {  }
  delete_value:
    - parents: hidden:config
      values:
        - field_d_long_text
        - field_d_main_title
core.entity_view_display.paragraph.d_p_side_by_side.default:
  add:
    content:
      field_d_long_text:
        type: text_textarea
        weight: 1
        region: content
        settings:
          rows: 5
          placeholder: ''
        third_party_settings: {  }
      field_d_main_title:
        type: string_textfield
        weight: 0
        region: content
          settings:
            size: 60
            placeholder: ''
          third_party_settings: {  }
  delete_value:
    - parents: hidden:config
      values:
        - field_d_long_text
        - field_d_main_title
