core.entity_form_display.paragraph.d_p_side_by_side.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_side_by_side.field_d_main_title
        - field.field.paragraph.d_p_side_by_side.field_d_long_text
      module:
        - link_attributes
        - media_library
    third_party_settings:
      field_group:
        group_settings:
          children:
            - field_d_main_title
            - field_d_long_text
    content:
      field_d_long_text:
        type: text_default
        weight: 3
        region: content
        label: hidden
        settings: {  }
        third_party_settings: {  }
      field_d_main_title:
        type: string
        weight: 4
        region: content
        label: hidden
        settings:
          link_to_entity: false
        third_party_settings: {  }
core.entity_view_display.paragraph.d_p_side_by_side.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_side_by_side.field_d_main_title
        - field.field.paragraph.d_p_side_by_side.field_d_long_text
      module:
        - link
    content:
      field_d_long_text:
        type: text_default
        weight: 3
        region: content
        label: hidden
        settings: {  }
        third_party_settings: {  }
      field_d_main_title:
        type: string
        weight: 4
        region: content
        label: hidden
        settings:
          link_to_entity: false
        third_party_settings: {  }
