core.entity_view_display.paragraph.d_p_side_by_side.default:
  change:
    expected:
      content:
        field_d_media_icon:
          weight: 7
    new:
      content:
        field_d_media_icon:
          weight: 0
