core.entity_form_display.paragraph.d_p_side_by_side.default:
  delete_value:
    - parents: hidden:config
      values:
        - field_d_long_text
        - field_d_main_title
core.entity_view_display.paragraph.d_p_side_by_side.default:
  delete_value:
    - parents: hidden:config
      values:
        - field_d_long_text
        - field_d_main_title
