block.block.mobilefilterssubmit:
  change:
    expected:
      region: facets_top
    new:
      region: facets_left

# Try to update the same block for subtheme.
block.block.droopler_subtheme_mobilefilterssubmit:
  change:
    expected:
      region: facets_top
    new:
      region: facets_left
