info:
  type: content_page
  title: Product
field_page_section:
  paragraphs:
    - paragraph_type: d_p_side_image
      data:
        field_d_main_title:
          type: text
          data: Electric engine for production
        field_d_image_background:
          type: image
          data: d_demo/demo_business_3.jpg
          dst_dir: demo
        field_d_p_si_image_side:
          type: text_select
          data: right-wide
        field_d_long_text:
          type: text_long
          data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent bibendum mi elit,
            id commodo ligula viverra vitae. Aliquam lorem diam, lobortis at ante et,
            gravida blandit enim.</p>
        field_d_background_color:
          type: color
          data: '#ffffff'
        field_d_cta_link:
          type: cta
          data:
            link: internal:/documentation/sidebar-image-paragraph
            text: Meet our engines
            options:
              attributes:
                class:
                  - "btn"
                  - "btn-danger"
                  - "mt-4"
                target: "_blank"
        field_d_settings:
          type: field_p_configuration_storage
          custom_class: with-alt-line with-alt-text

    - paragraph_type: d_p_text_paged
      data:
        field_d_main_title:
          type: text
          data: We are an exert in Electric engines
        field_d_long_text:
          type: text_long
          data: <p>Experience marked by 20 years on the market<br />- wide range of products</p>
        field_d_settings:
          type: field_p_configuration_storage
          custom_class: with-alt-line

    - paragraph_type: d_p_side_by_side
      data:
        field_d_settings:
          type: field_p_configuration_storage
          custom_class: full-width with-grid with-alt-line no-padding-top
        field_d_p_sbs_items:
          type: paragraph_reference
          subtype: paragraphs_wrapper
          data:
            - type: d_p_node
              data:
                field_d_display_mode:
                  type: text_select
                  data: d_small_box
                field_d_node_reference:
                  type: entity_reference
                  data:
                    - target_id: 23
            - type: d_p_single_text_block
              data:
                field_d_main_title:
                  type: text
                  data: Centurion V750
                field_d_long_text:
                  type: text_long
                  data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent bibendum mi elit,
                    id commodo ligula viverra vitae. Aliquam lorem diam, lobortis at ante et, gravida blandit enim.
                    Ut bibendum egestas sem. Nulla porttitor lorem in erat maximus, id vulputate est auctor. Curabitur
                    consectetur nec ante ac ornare. Nam aliquam elit ex. Nam feugiat nulla pulvinar nunc commodo,
                    eget faucibus mauris egestas.</p>
                    <p><ul>
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Aliquam lorem diam</li>
                    <li>Nulla porttitor lorem in erat</li>
                    <li>Nam feugiat nulla pulvinar</li>
                    </ul>
                    </p>
                field_d_background_color:
                  type: color
                  data: '#e4e4e4'
