info:
  type: content_page
  title: Product
field_page_section:
  paragraphs:
    - paragraph_type: d_p_side_image
      data:
        field_d_main_title:
          type: text
          data: Electric engine for manufacturing
        field_d_image_background:
          type: image
          data: d_demo/demo_business_3.jpg
          dst_dir: demo
        field_d_p_si_image_side:
          type: text_select
          data: right-wide
        field_d_long_text:
          type: text_long
          data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent bibendum mi elit,
            id commodo ligula viverra vitae. Aliquam lorem diam, lobortis at ante et,
            gravida blandit enim.</p>
        field_d_background_color:
          type: color
          data:
            color: '#ffffff'
            opacity: 1
        field_d_cta_link:
          type: cta
          data:
            link: internal:/documentation/sidebar-image-paragraph
            text: Meet our engines
            options:
              attributes:
                class:
                  - "btn"
                  - "btn-danger"
                  - "mt-4"
                target: "_blank"
        field_d_settings:
          type: field_p_configuration_storage
          custom_class: with-alt-line with-alt-text

