core.entity_form_display.paragraph.d_p_reference_content.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_reference_content.field_d_long_text
        - field.field.paragraph.d_p_reference_content.field_d_media_icon
      module:
        - media_library
        - text
    content:
      field_d_long_text:
        weight: 2
        settings:
          rows: 5
          placeholder: ''
        third_party_settings: {  }
        type: text_textarea
        region: content
      field_d_media_icon:
        weight: 0
        settings:
          media_types: {  }
        third_party_settings: {  }
        type: media_library_widget
        region: content
core.entity_view_display.paragraph.d_p_reference_content.default:
  add:
    dependencies:
      config:
        - field.field.paragraph.d_p_reference_content.field_d_long_text
        - field.field.paragraph.d_p_reference_content.field_d_media_icon
      module:
        - text
    content:
      field_d_long_text:
        weight: 2
        label: hidden
        settings: {  }
        third_party_settings: {  }
        type: text_default
        region: content
      field_d_media_icon:
        weight: 0
        label: hidden
        settings:
          view_mode: d_icon
          link: false
        third_party_settings: {  }
        type: entity_reference_entity_view
        region: content
