type: content_page
title: Product Landing Page Example
field_page_section:
  paragraphs:
  - paragraph_type: d_p_banner
    data:
      field_d_main_title:
        type: text
        data: Enjoy Life And Your Ride
      field_d_subtitle:
        type: text
        data: Product Landing Page Example
      field_d_image_background:
        type: image
        data: demo_1.JPG
      field_d_long_text:
        type: text_long
        data: This page is the example of a product landing page, the showcase of a single item from your offer.
          It contains lots of high-quality photos and shows all the advantages and qualities.
          The desired reaction of the viewer is a purchase.
      field_d_cta_link:
        type: cta
        data:
          link: internal:/node/1
          text: Buy now
  - paragraph_type: d_p_group_of_text_blocks
    data:
      field_d_main_title:
        type: text
        data: Innovation and Technology
      field_d_cta_link:
        type: cta
        data:
          link: internal:/node/5
          text: Take a test ride
      field_d_p_tb_block_reference:
        type: paragraph_reference
        data:
        - field_d_main_title:
            type: text
            data: Safety
          field_d_long_text:
            type: text_long
            data: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.
          field_d_cta_link:
            type: cta
            data:
              link: internal:/node/2
              text: More
        - field_d_main_title:
            type: text
            data: Engines
          field_d_long_text:
            type: text_long
            data: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.
          field_d_cta_link:
            type: cta
            data:
              link: internal:/node/2
              text: More
        - field_d_main_title:
            type: text
            data: The package
          field_d_long_text:
            type: text_long
            data: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.
          field_d_cta_link:
            type: cta
            data:
              link: internal:/node/2
              text: More
        - field_d_main_title:
            type: text
            data: Colors
          field_d_long_text:
            type: text_long
            data: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.
          field_d_cta_link:
            type: cta
            data:
              link: internal:/node/2
              text: More
        - field_d_main_title:
            type: text
            data: Drive
          field_d_long_text:
            type: text_long
            data: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.
          field_d_cta_link:
            type: cta
            data:
              link: internal:/node/2
              text: More
        - field_d_main_title:
            type: text
            data: Service
          field_d_long_text:
            type: text_long
            data: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.
          field_d_cta_link:
            type: cta
            data:
              link: internal:/node/2
              text: More
  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: Comfort when onboarding
      field_d_image_background:
        type: image
        data: demo_2.JPG
      field_d_p_si_image_side:
        type: text_select
        data: left
      field_d_long_text:
        type: text_long
        data: Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.
  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: Focus on the road
      field_d_image_background:
        type: image
        data: demo_5.JPG
      field_d_p_si_image_side:
        type: text_select
        data: right
      field_d_long_text:
        type: text_long
        data: Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.
  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: All under control
      field_d_image_background:
        type: image
        data: demo_6.JPG
      field_d_p_si_image_side:
        type: text_select
        data: left
      field_d_long_text:
        type: text_long
        data: Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.
  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: Authentic pleasure of driving
      field_d_image_background:
        type: image
        data: demo_7.JPG
      field_d_p_si_image_side:
        type: text_select
        data: right
      field_d_long_text:
        type: text_long
        data: Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.
  - paragraph_type: d_p_text_paged
    data:
      field_d_main_title:
        type: text
        data: Perfect trip is just around the corner!
  - paragraph_type: d_p_banner
    data:
      field_d_main_title:
        type: text
        data: Your turn
      field_d_subtitle:
        type: text
        data: Schedule a test ride. It is your decision which road to take and how
          fast you go!
      field_d_image_background:
        type: image
        data: demo_1.JPG
      field_d_long_text:
        type: text_long
        data: ''
      field_d_cta_link:
        type: cta
        data:
          link: internal:/node/5
          text: Contact Us
